### ISSUE TITLE
Expected finish time for processing one single index of commoncrawl?

### ISSUE THREAD

**Issue by kimcando** [togethercomputer/RedPajama-Data#35]
One more question, please.

using the provided command, how long does it take to finish the each step(e.g, quality filtering, deduplication, quality classifier) for processing single index of commoncrawl(e.g, 2023-06 ) ? 

Thank you!

**Comment by mauriceweber** [comment]
we used a machine with 64 cores and 512GB RAM and it took about 2-3 days for one CC dump to process with the cc_net pipeline. You can expect another day for deduplication and applying the quality classifier.

You can use the quality classifier that we have trained, so that you don't have to retrain it ([this](https://github.com/togethercomputer/RedPajama-Data/tree/main/data_prep/cc#:~:text=We%20then%20classify%20each%20CommonCrawl%20webpage%20using%20the%20trained%20classifier.%20The%20model%20weights%20can%20be%20downloaded%20here.) part of the readme points you the model).

**Comment by newbietuan** [comment]
> 

hello, how much the disk space will need?  about 100T?

**Comment by kimcando** [comment]
@mauriceweber a single machine with 64 cores and 512 GB? for a single index?

**Comment by mauriceweber** [comment]
yes, this is correct.
