### ISSUE TITLE
Question about Size Difference of arXiv Data in RedPajama and AWS S3

### ISSUE THREAD

**Issue by Mr-Philo** [togethercomputer/RedPajama-Data#40]
Hello there, thank you for your work! 

I noticed that the **arXiv** data used in RedPajama was download from AWS S3 (https://info.arxiv.org/help/bulk_data_s3.html), which states that the complete set of files as of March 2023 is about **5.6 TB**. However, I downloaded the preprocessed arXiv jsonl file (from this RedPajama link: https://data.together.xyz/redpajama-data-1T/v1.0.0/urls.txt) and found that the total disk size of arXiv jsonl file is only **87.35GB**. 

So, I am wondering how this huge gap comes from. There are two possibilities that I can think of:
1. RedPajama data may have used only **a subset of** the arXiv AWS S3 data.
2. The cleaning code and deduplication metrics used may have been **so strict** that most of the arXiv data was cleaned.

I would appreciate it if you could help answer my question. Thanks a lot!

**Comment by mauriceweber** [comment]
Hi! Thanks for your question!

If you download the raw arxiv/src data from S3, you will also get figures and some arxiv articles which were submitted as pdf (instead of tex files). In RP, we only include the .tex sources and discard everything else. Once we have the sources, we also remove everything before the first appearance of a section-like header, and everything after (and including) the bibliography.

Also, the 5.6T mentioned in https://info.arxiv.org/help/bulk_data_s3.html refers to both the src files, and the processed pdfs (resulting from the src files). We processed only the src part which is 2.9T.

Let me know if this clarifies your question!

**Comment by Mr-Philo** [comment]
> Hi! Thanks for your question!
> 
> If you download the raw arxiv/src data from S3, you will also get figures and some arxiv articles which were submitted as pdf (instead of tex files). In RP, we only include the .tex sources and discard everything else. Once we have the sources, we also remove everything before the first appearance of a section-like header, and everything after (and including) the bibliography.
> 
> Also, the 5.6T mentioned in https://info.arxiv.org/help/bulk_data_s3.html refers to both the src files, and the processed pdfs (resulting from the src files). We processed only the src part which is 2.9T.
> 
> Let me know if this clarifies your question!

Thank you for your answer! I've figured out my question now 😄
